name: execute the Ansible playbooks
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: run playbook
        shell: bash
        run: |
          ls -la
